# This is a basic workflow to help you get started with Actions

name: Project Zircon Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main 
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  systemtest:
    name: SystemTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Running SystemTests
        run: python3 -m unittest test/SystemTests/*
        
  interceptortest:
    name: InterceptorTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running SystemTests
        run: python3 -m unittest test/InterceptorTest/*

  entitytest:
    name: EntityTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running EntityTests
        run: python3 -m unittest test/EntityTest/*

  enginetest:
    name: EngineTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running EngineTests
        run: python3 -m unittest test/EngineTests/*
        
  componenttest:
    name: ComponentTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running ComponentTests
        run: python3 -m unittest test/ComponentTests/*

