name: Project Zircon Unit Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main 
    - master

  workflow_dispatch:

jobs:
  installpython:
    name: Install Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
  test: 
      name: SystemTests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Running Tests
          run: |
            pip install tcod
            pip install numpy
            python3 -m unittest test/*

  
